# Generated by Django 5.2.9 on 2025-12-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_served',
        ),
        migrations.AddField(
            model_name='ticket',
            name='file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='service_type',
            field=models.CharField(choices=[('GENEL', 'Genel İşlemler'), ('GISE', 'Gişe İşlemleri'), ('OZEL', 'Özel Müşteri')], default='GENEL', max_length=20),
        ),
    ]
